<?php
/**
 * Created by PhpStorm.
 * User: afinogen
 * Date: 12.04.16
 * Time: 16:32
 */

namespace app\components;


/**
 * Class EmailEvent
 *
 * @package app\components
 */
class EmailEvent extends BasicEvent
{
    const EVENT_TYPE_EMAIL = 'email';
    
    public static function generateEvents($event, $object)
    {
        $res =  parent::generateEvents($event, $object); // TODO: Change the autogenerated stub
        if ($res) {
            self::sendMail();
        }
        
        return $res;
    }

    public static function sendMail()
    {
        
    }
}