<?php
/**
 * Created by PhpStorm.
 * User: afinogen
 * Date: 12.04.16
 * Time: 16:32
 */

namespace app\components;


/**
 * Class EmailEvent
 * События для отправки на E-mail
 *
 * @package app\components
 */
class EmailEvent extends BasicEvent
{
    const EVENT_TYPE_EMAIL = 'email';

    /**
     * @param \app\models\Event $event
     * @param $object
     * @param \app\models\EventType $type
     * @return bool
     */
    public static function generateEvents($event, $object, $type)
    {
        $res =  parent::generateEvents($event, $object, $type); // TODO: Change the autogenerated stub
        if ($res) {
            self::sendMail();
        }
        
        return $res;
    }

    /**
     * Здесь будет отправка на почту
     */
    public static function sendMail()
    {
        
    }
}